service: pages-api

plugins:
  - serverless-python-requirements

package:
  exclude:
    - '**'
  include:
    - src/**

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  app:
    handler: src.app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'